[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
via_ir = true
verbosity = 3
remappings = [
    'src/=src/'
]

[profile.e2e]
match_path = "test/e2e/*"

[profile.unit]
block_number = 17373196
block_timestamp = 1685467379
match_path = "test/unit/*"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
arbitrumOne = "${RPC_ARBITRUM}"
arbitrumOneTestnet = "${RPC_ARBITRUM_GOERLI}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1, url = "https://api.etherscan.io/api/"}
goerli = { key = "${ETHERSCAN_KEY}", chain = 5, url = "https://api-goerli.etherscan.io/api/"}
arbitrumOne = { key = "${ARBISCAN_KEY}", chain = 42161, url = "https://api.arbiscan.io/api/"}
arbitrumGoerli = { key = "${ARBISCAN_KEY}", chain = 421613, url = "https://api-goerli.arbiscan.io/api/"}


[fmt]
line_length = 90
tab_width = 2
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config