[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.25'
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
via_ir = true
verbosity = 3
auto_detect_remappings = true

# Foundry 1.0 has Optimizer disabled by default
#optimizer = true 
#optimizer_runs = 200 

[profile.e2e]
match_path = "test/e2e/*"

[profile.unit]
block_number = 17373196
block_timestamp = 1685467379
match_path = "test/unit/*"

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
arbitrum = "${RPC_ARBITRUM}"
arbitrumTestnet = "${RPC_ARBITRUM_SEPOLIA}"
bsc = "${RPC_BSC}"
bscTestnet = "${RPC_BSC_TESTNET}"
polygon = "${RPC_POLYGON}"
polygonTestnet = "${RPC_POLYGON_TESTNET}"
gnosis = "${RPC_GNOSIS}"
gnosisTestnet = "${RPC_GNOSIS_TESTNET}"

[etherscan]
ethereum = { key = "${ETHERSCAN_KEY}", chain = 1 }
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111 }
bsc = { key = "${ETHERSCAN_KEY}", chain = 56 }
bscTestnet = { key = "${ETHERSCAN_KEY}", chain = 97 }
polygon = { key = "${ETHERSCAN_KEY}", chain = 137 }
polygonTestnet = { key = "${ETHERSCAN_KEY}", chain = 80001 }
optimistic = { key = "${ETHERSCAN_KEY}", chain = 10 }
optimismTestnet = { key = "${ETHERSCAN_KEY}", chain = 420 }
arbitrum = { key = "${ETHERSCAN_KEY}", chain = 42161 }
arbitrumSepolia = { key = "${ETHERSCAN_KEY}", chain = 421614 }
gnosis = { key = "${ETHERSCAN_KEY}", chain = 100 }
gnosisTestnet = { key = "${ETHERSCAN_KEY}", chain = 10200 }

[fmt]
line_length = 90
tab_width = 2
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config