[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.25'
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
via_ir = true
verbosity = 3
auto_detect_remappings = true

[profile.e2e]
match_path = "test/e2e/*"

[profile.unit]
block_number = 17373196
block_timestamp = 1685467379
match_path = "test/unit/*"

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
arbitrum = "${RPC_ARBITRUM}"
arbitrumTestnet = "${RPC_ARBITRUM_SEPOLIA}"
holesky = "${RPC_HOLESKY}"
bsc = "${RPC_BSC}"
bscTestnet = "${RPC_BSC_TESTNET}"
polygon = "${RPC_POLYGON}"
polygonTestnet = "${RPC_POLYGON_TESTNET}"
zkEVM = "${RPC_ZKEVM}"
zkEVMTestnet = "${RPC_ZKEVM_TESTNET}"
base = "${RPC_BASE}"
baseTestnet = "${RPC_BASE_TESTNET}"
novaArbiscan = "${RPC_NOVA_ARBISCAN}"
linea = "${RPC_LINEA}"
lineaTestnet = "${RPC_LINEA_TESTNET}"
ftm = "${RPC_FTM}"
ftmTestnet = "${RPC_FTM_TESTNET}"
blast = "${RPC_BLAST}"
blastTestnet = "${RPC_BLAST_TESTNET}"
optimistic = "${RPC_OPTIMISTIC}"
optimisticSepolia = "${RPC_OPTIMISTIC_SEPOLIA}"
snow = "${RPC_SNOW}"
snowTestnet = "${RPC_SNOW_TESTNET}"
bttc = "${RPC_BTTC}"
donauBttc = "${RPC_DONAU_BTTC}"
celo = "${RPC_CELO}"
alfajoresCelo = "${RPC_ALFAJORES_CELO}"
cronos = "${RPC_CRONOS}"
frax = "${RPC_FRAX}"
fraxTestnet = "${RPC_FRAX_TESTNET}"
gnosis = "${RPC_GNOSIS}"
kroma = "${RPC_KROMA}"
kromaTestnet = "${RPC_KROMA_TESTNET}"
mantle = "${RPC_MANTLE}"
mantleTestnet = "${RPC_MANTLE_TESTNET}"
moonbeam = "${RPC_MOONBEAM}"
moonriver = "${RPC_MOONRIVER}"
moonbase = "${RPC_MOONBASE}"
opbnb = "${RPC_OPBNB}"
opbnbTestnet = "${RPC_OPBNB_TESTNET}"
scroll = "${RPC_SCROLL}"
scrollTestnet = "${RPC_SCROLL_TESTNET}"
taiko = "${RPC_TAIKO}"
taikoTestnet = "${RPC_TAIKO_TESTNET}"
wemix = "${RPC_WEMIX}"
wemixTestnet = "${RPC_WEMIX_TESTNET}"
zkSync = "${RPC_ZKSYNC}"
zkSyncTestnet = "${RPC_ZKSYNC_TESTNET}"
xai = "${RPC_XAI}"
xaiSepolia = "${RPC_XAI_SEPOLIA}"

[etherscan]
ethereum = { key = "${ETHERSCAN_KEY}", chain = 1, url = "https://api.etherscan.io/v2/api"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111, url = "https://api.etherscan.io/v2/api"}
holesky = { key = "${ETHERSCAN_KEY}", chain = 17000, url = "https://api.etherscan.io/v2/api"}
#[BSC]
bsc = { key = "${ETHERSCAN_KEY}", chain = 56, url = "https://api.etherscan.io/v2/api"}
bscTestnet = { key = "${ETHERSCAN_KEY}", chain = 97, url = "https://api.etherscan.io/v2/api"}
#[polygon]
polygon = { key = "${ETHERSCAN_KEY}", chain = 137, url = "https://api.etherscan.io/v2/api"}
polygonTestnet = { key = "${ETHERSCAN_KEY}", chain = 80002, url = "https://api.etherscan.io/v2/api"}
#[zkEVM]
zkEVM = { key = "${ETHERSCAN_KEY}", chain = 1101, url = "https://api.etherscan.io/v2/api"}
zkEVMTestnet = { key = "${ETHERSCAN_KEY}", chain = 2442, url = "https://api.etherscan.io/v2/api"}
#[baseScan]
base = { key = "${ETHERSCAN_KEY}", chain = 8453, url = "https://api.etherscan.io/v2/api"}
baseTestnet = { key = "${ETHERSCAN_KEY}", chain = 84532, url = "https://api.etherscan.io/v2/api"}
#[arbiscan]
arbitrum = { key = "${ETHERSCAN_KEY}", chain = 42161, url = "https://api.etherscan.io/v2/api"}
novaArbiscan = { key = "${ETHERSCAN_KEY}", chain = 42170, url = "https://api.etherscan.io/v2/api"}
arbitrumSepolia = { key = "${ETHERSCAN_KEY}", chain = 421614, url = "https://api.etherscan.io/v2/api"}
#[lineaScan]
linea = { key = "${ETHERSCAN_KEY}", chain = 59144, url = "https://api.etherscan.io/v2/api"}
lineaTestnet = { key = "${ETHERSCAN_KEY}", chain = 59141, url = "https://api.etherscan.io/v2/api"}
#[ftmScan]
ftm = { key = "${ETHERSCAN_KEY}", chain = 250, url = "https://api.etherscan.io/v2/api"}
ftmTestnet = { key = "${ETHERSCAN_KEY}", chain = 4002, url = "https://api.etherscan.io/v2/api"}
#[blastScan]
blast = { key = "${ETHERSCAN_KEY}", chain = 81457, url = "https://api.etherscan.io/v2/api"}
blastTestnet = { key = "${ETHERSCAN_KEY}", chain = 168587773, url = "https://api.etherscan.io/v2/api"}
#[optimisticEtherscan]
optimistic = { key = "${ETHERSCAN_KEY}", chain = 10, url = "https://api.etherscan.io/v2/api"}
optimisticSepolia = { key = "${ETHERSCAN_KEY}", chain = 11155420, url = "https://api.etherscan.io/v2/api"}
#[snowScan]
snow = { key = "${ETHERSCAN_KEY}", chain = 43114, url = "https://api.etherscan.io/v2/api"}
snowTestnet = { key = "${ETHERSCAN_KEY}", chain = 43113, url = "https://api.etherscan.io/v2/api"}
#[bttcScan]
bttc = { key = "${ETHERSCAN_KEY}", chain = 199, url = "https://api.etherscan.io/v2/api"}
donauBttc = { key = "${ETHERSCAN_KEY}", chain = 1028, url = "https://api.etherscan.io/v2/api"}
#[celoScan]
celo = { key = "${ETHERSCAN_KEY}", chain = 42220, url = "https://api.etherscan.io/v2/api"}
alfajoresCelo = { key = "${ETHERSCAN_KEY}", chain = 44787, url = "https://api.etherscan.io/v2/api"}
#[cronoscan]
cronos = { key = "${ETHERSCAN_KEY}", chain = 25, url = "https://api.etherscan.io/v2/api"}
#[fraxscan]
frax = { key = "${ETHERSCAN_KEY}", chain = 252, url = "https://api.etherscan.io/v2/api"}
fraxTestnet = { key = "${ETHERSCAN_KEY}", chain = 2522, url = "https://api.etherscan.io/v2/api"}
#[gnosisScan]
gnosis = { key = "${ETHERSCAN_KEY}", chain = 100, url = "https://api.etherscan.io/v2/api"}
#[kromaScan]
kroma = { key = "${ETHERSCAN_KEY}", chain = 255, url = "https://api.etherscan.io/v2/api"}
kromaTestnet = { key = "${ETHERSCAN_KEY}", chain = 2358, url = "https://api.etherscan.io/v2/api"}
#[mantlescan]
mantle = { key = "${ETHERSCAN_KEY}", chain = 5000, url = "https://api.etherscan.io/v2/api"}
mantleTestnet = { key = "${ETHERSCAN_KEY}", chain = 5003, url = "https://api.etherscan.io/v2/api"}
#[moonbeamScan]
moonbeam = { key = "${ETHERSCAN_KEY}", chain = 1284, url = "https://api.etherscan.io/v2/api"}
#[moonriverScan]
moonriver = { key = "${ETHERSCAN_KEY}", chain = 1285, url = "https://api.etherscan.io/v2/api"}
#[moonbaseScan]
moonbase = { key = "${ETHERSCAN_KEY}", chain = 1287, url = "https://api.etherscan.io/v2/api"}
#[opbnbBscScan]
opbnb = { key = "${ETHERSCAN_KEY}", chain = 204, url = "https://api.etherscan.io/v2/api"}
opbnbTestnet = { key = "${ETHERSCAN_KEY}", chain = 5611, url = "https://api.etherscan.io/v2/api"}
#[scrollScan]
scroll = { key = "${ETHERSCAN_KEY}", chain = 534352, url = "https://api.etherscan.io/v2/api"}
scrollTestnet = { key = "${ETHERSCAN_KEY}", chain = 534351, url = "https://api.etherscan.io/v2/api"}
#[taikoScan]
taiko = { key = "${ETHERSCAN_KEY}", chain = 167000, url = "https://api.etherscan.io/v2/api"}
taikoTestnet = { key = "${ETHERSCAN_KEY}", chain = 167009, url = "https://api.etherscan.io/v2/api"}
#[wemixScan]
wemix = { key = "${ETHERSCAN_KEY}", chain = 1111, url = "https://api.etherscan.io/v2/api"}
wemixTestnet = { key = "${ETHERSCAN_KEY}", chain = 1112, url = "https://api.etherscan.io/v2/api"}
#[zkSyncEra]
zkSync = { key = "${ETHERSCAN_KEY}", chain = 324, url = "https://api.etherscan.io/v2/api"}
zkSyncTestnet = { key = "${ETHERSCAN_KEY}", chain = 300, url = "https://api.etherscan.io/v2/api"}
#[xaiScan]
xai = { key = "${ETHERSCAN_KEY}", chain = 660279, url = "https://api.etherscan.io/v2/api"}
xaiSepolia = { key = "${ETHERSCAN_KEY}", chain = 37714555429, url = "https://api.etherscan.io/v2/api"}

[fmt]
line_length = 90
tab_width = 2
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config